#!/bin/bash
# Asher Bond 2011 
# Configuration Manager: elastic-paas dev environment
# License: AGPL v3
# assumes Ubuntu 10.04.3 LTS pristine system imagery
# a fork of https://raw.github.com/AsherBond/vcap/master/dev_setup/bin/vcap_dev_setup


if [ -n "$http_proxy" ]; then
  if [ -z "$https_proxy" ]; then
    echo "Please set https_proxy env variable."
    exit 1
  fi
  PROXY=$http_proxy
fi

APT_CONFIG="-o Acquire::http::No-Cache=True -o Acquire::BrokenProxy=true -o Acquire::Retries=3"

if [ -z "$CLOUDFOUNDRY_HOME" ]; then
  CLOUDFOUNDRY_HOME=~/cloudfoundry
fi

if [ -z "$VCAP_REPO" ]; then
  VCAP_REPO=https://github.com/AsherBond/vcap.git
fi

function run_cmd () {
  if [ -z "$PROXY" ]; then
    sudo $*
  else
    sudo env http_proxy=$PROXY $*
  fi
}


sudo apt-get install -y wget
which chef-solo
if [ $? != 0 ]; then
  echo "deb http://apt.opscode.com/ `lsb_release -cs`-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list
  wget -qO - http://apt.opscode.com/packages@opscode.com.gpg.key | sudo apt-key add -
  echo chef chef/chef_server_url select none | sudo /usr/bin/debconf-set-selections
  run_cmd apt-get $APT_CONFIG update
  run_cmd apt-get $APT_CONFIG install -qym chef
else
  run_cmd apt-get $APT_CONFIG update
fi

run_cmd apt-get $APT_CONFIG install -qym git-core
[ -d $CLOUDFOUNDRY_HOME ] || mkdir $CLOUDFOUNDRY_HOME
if [ ! -d $CLOUDFOUNDRY_HOME/vcap ]; then
   (cd $CLOUDFOUNDRY_HOME && git clone $VCAP_REPO && cd vcap && git submodule update --init)
    if [ $? != 0 ]; then
      echo "Unable to clone cloudfoundry repo."
      exit 1
    fi
fi


# Our deployment code needs this gem. Using bundler seems like an overkill for
# the deployment code. So for now just manually install the required gem.
gem list rake -i > /dev/null
if [ $? != 0 ]; then
  gem install rake -q --no-ri --no-rdoc > /dev/null 2>&1
fi

# Launch chef
ARGS=""
if [ -n "$CLOUDFOUNDRY_HOME" ]; then
  ARGS="-d $CLOUDFOUNDRY_HOME"
fi

if [ -n "$CONFIG_FILE" ]; then
  ARGS="$ARGS -c $CONFIG_FILE"
fi

$CLOUDFOUNDRY_HOME/vcap/dev_setup/lib/chefsolo_launch.rb $ARGS


