#!/bin/bash
# Asher Bond 2011 
# ep-gitstrapped
# Configuration Manager: elastic provisioner runtime bootstrapper
# "A loaded gun without a waiting period" - @ElasticYotta
# License: AGPL v3
# assumes Ubuntu 10.04 LTS pristine system imagery (tested on 10.04.3)
# SYNTAX: ep-gitstrapped <strap>


# change this to your elastic provisioner repo if you want
ep_repo='https://gitstrapped.elasticprovisioner.com'

# rely on apt for package management, but not too much
apt-get update
apt-get -y upgrade

# at this point we should have the generic kernel upgraded

# now lets pull from some repos
apt-get install -y git-core curl

strap=$1
shift

if [ ! -z $1 ]; then
	curl -s -k -B "$ep_repo/$strap" | bash -s $*
else	curl -s -k -B "$ep_repo/$strap" | bash
fi
